const askAI = require("../ai/askAi");
const formatResponse = require("../utils/formatter");
const ora = require("ora");
const { exec } = require("child_process");
const { isDangerous, isRisky, analyzeCommand } = require("../utils/safety");
const confirmExecution = require("../utils/conformation");
const {
    tryResolveWithoutAi,
    finalizeWithAi,
    isInvalidAiResponse,
    sanitizeAiCommand
} = require("../utils/intentRouter");


async function commandGen(query, options){
    const spinner = ora("Generating command...").start();
    try {
        const prompt = `
    You are a Linux expert.
    
    Convert this into a shell command.
    
    Rules:
    - Only output the command
    - No explanation
    - No extra text
    - Prefer safe, common Linux commands
    - Never output shutdown/reboot/rm -rf/mkfs/dd unless user explicitly asked
    
    Query: ${query}
    `;

        const hybridOpts = {
            isInvalidResponse: isInvalidAiResponse,
            sanitizeCommand: sanitizeAiCommand
        };

        let { command: result, source } = tryResolveWithoutAi(query, hybridOpts);
        let aiProvider = null;
        if (!result) {
            const aiResponse = await askAI(prompt);
            const aiResult = aiResponse.text.trim();
            aiProvider = aiResponse.provider;
            ({ command: result, source } = finalizeWithAi(query, aiResult, hybridOpts));
        }
        if (!result) {
            spinner.stop();
            console.log("❌ Unable to generate a reliable command right now. Please try again.");
            return;
        }

        spinner.stop();
        
        // Analyze command safety
        const safety = analyzeCommand(result.trim());
        
        // Show trust indicator
        if (safety.level === 'safe') {
            console.log('\n✅ Safe command');
        } else if (safety.level === 'risky') {
            console.log('\n⚠️  Review recommended');
        }
        
        formatResponse("Generated Command", result.trim());
        
        // Show safety explanation
        if (safety.warning) {
            console.log(safety.warning);
        }
        console.log(`🔍 ${safety.explanation}`);
        
        if (source === "cache") {
            console.log("⚡ Served from cache for instant response.");
        } else if (source === "local") {
            console.log("ℹ️ Used local intent handler for faster response.");
        } else if (source === "fallback") {
            console.log("ℹ️ Used local fallback because AI was unavailable.");
        } else if (source === "ai") {
            const providerName = aiProvider === 'ollama' ? 'local AI (Ollama)' : 'cloud AI (Gemini)';
            console.log(`🤖 Generated by ${providerName}`);
        }
        
        console.log("💡 Tip: Review commands before executing. Use --copy to copy, --run to execute.");

        if(options.copy){
            const clipboard = (await import("clipboardy")).default;
            clipboard.writeSync(result);
            console.log("📋 Command copied to clipboard!");
        }

        if(options.run){
            const safety = analyzeCommand(result);
            
            if(safety.level === 'dangerous'){
                console.log("\n❌ Dangerous command blocked for your safety!");
                console.log(`   Reason: ${safety.explanation}`);
                console.log("   If you're sure, run this command manually.");
                return;
            }
            
            if (typeof confirmExecution !== "function") {
                console.log("❌ Execution confirmation is not configured correctly.");
                return;
            }

            console.log();
            if (safety.level === 'risky') {
                console.log("⚠️  WARNING: This command may modify or delete files!");
            }
            
            const confirm = await confirmExecution(result);
            if(!confirm) {
                console.log("❌ Execution cancelled.");
                return;
            }
            
            console.log("\n▶️  Executing command...\n");

            exec(result, (error, stdout, stderr) => {
                if(error){
                    console.log("❌ Error:", error.message);
                    console.log("💡 Tip: Use 'shellbuddy fix' to get help with this error.");
                }
                if (stdout) console.log(stdout);
                if (stderr) console.log(stderr);
            })
        }
    } catch (error) {
        spinner.stop();
        console.error("Error in generating command", error);
    }
}



module.exports = commandGen;